import { bundles, counts, validate } from "../src/data";
import * as fs from "node:fs";
const lines: string[] = [];
lines.push("# Coverage checklist", "", "Generated by `npx tsx scripts/coverage.ts`. Every area of Dark Souls II: Scholar of the First Sin with the number of records entered from the wikis (Fextralife SotFS pages first, wikidot for cross-checks). Counts are per record; an item record with `qty` counts once.", "");
lines.push(`Totals: ${counts.areas} areas · ${counts.bonfires} bonfires · ${counts.bosses} bosses · ${counts.items} items · ${counts.npcs} NPC records · ${counts.features} features · ${counts.edges} graph edges · ${counts.enemies} farmable enemies.`, "");
lines.push("| Area | DLC | Bonfires | Bosses | Items | NPCs | Features | Nodes | Edges | Status | Source |", "|---|---|---|---|---|---|---|---|---|---|---|");
for (const b of bundles) {
  const status = b.items.length === 0 && b.area.id !== "chasm" && b.area.id !== "old_chaos" && b.area.id !== "throne" ? "⚠ no items" : "✔ wiki pickups entered";
  lines.push(`| ${b.area.name} | ${b.area.dlc ?? ""} | ${b.bonfires.length} | ${b.bosses.length} | ${b.items.length} | ${b.npcs.length} | ${b.features.length} | ${b.nodes.length} | ${b.edges.length} | ${status} | ${b.area.source} |`);
}
lines.push("", "## Notes", "",
  "- Bonfires: 77 regular + 4 Primal Bonfires = 81 (Fextralife's Bonfires page lists 77 named bonfires; Primal Bonfires are added as their own records). Belfry Sol Approach is filed under Belfry Sol, Sanctum Interior under Dragon's Rest, as on Fextralife's Bonfires page.",
  "- Bosses: 41 (32 base-game + 9 DLC, per Fextralife's Bosses page). The Pursuer's repeat encounters (Iron Keep, Things Betwixt, Drangleic Castle, Lost Bastille) are recorded as features/notes, not extra bosses.",
  "- Items marked with a `note` saying 'Exact spot not given by the wiki' come from the page's item list but the walkthrough does not describe the location; the `howToReach` text gives the closest landmark.",
  "- Throne of Want, Old Chaos and Dark Chasm of Old have no ground pickups on the wiki (only boss drops / covenant rewards, which are recorded).",
  "- Enemy drops and farming spots are in `src/data/enemies.ts` with the despawn / Bonfire Ascetic / Company of Champions note.",
);
const problems = validate();
lines.push("", `Data validation: ${problems.length ? problems.join("; ") : "OK (all node/area references resolve, every record has a source)"}.`);
fs.writeFileSync("COVERAGE.md", lines.join("\n") + "\n");
console.log("COVERAGE.md written");
